# NOTE: create application.properties resource file! This is only template.

spring.application.name=dasig-core

spring.datasource.url=jdbc:postgresql://db.[YOUR_PROJECT_REF].supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=ENTER_YOUR_PASSWORD_HERE
