# NOTE: create application.properties resource file! This is only template.

spring.application.name=dasig-core

spring.datasource.url=jdbc:postgresql://db.[YOUR_PROJECT_REF].supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=ENTER_YOUR_PASSWORD_HERE
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#JWT
app.jwt-secret=ENTER_YOUR_JWT_SECRET_HERE
app.jwt-expiration-milliseconds=86400000

#SMTP Credentials
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ENTER_YOUR_GMAIL_ACCOUNT
# NOTE: This must be a 16-character "App Password", NOT your regular login password!
spring.mail.password=ENTER_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true